name: CI - shippingservice

on:
  push:
    branches:
      - main
    paths:
      - 'src/shippingservice/**'
      - '.github/workflows/ci-shippingservice.yaml'
      - '.github/workflows/build-push.yml'
  workflow_dispatch:

concurrency:
  group: ci-shippingservice-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-push-update:
    uses: ./.github/workflows/build-push.yml
    with:
      service: shippingservice
      context: src/shippingservice
    secrets: inherit